<?php /* Smarty version Smarty-3.1.7, created on 2016-11-28 09:44:15
         compiled from "/var/www/moihottur/data/www/crmturizm.ru/includes/runtime/../../layouts/vlayout/modules/Potentials/part/arrival_rows.tpl" */ ?>
<?php /*%%SmartyHeaderCode:21052237557ab43bfb813b9-12779743%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '69e90fe8118dee907d95b5370becc04c72f64158' => 
    array (
      0 => '/var/www/moihottur/data/www/crmturizm.ru/includes/runtime/../../layouts/vlayout/modules/Potentials/part/arrival_rows.tpl',
      1 => 1480092186,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '21052237557ab43bfb813b9-12779743',
  'function' => 
  array (
  ),
  'version' => 'Smarty-3.1.7',
  'unifunc' => 'content_57ab43bfc6a18',
  'variables' => 
  array (
    'opportunity_type' => 0,
    'check_array' => 0,
    'key_air' => 0,
    'width15' => 0,
    'BLOCK_FIELDS' => 0,
    'FIELD_MODEL' => 0,
    'FIELD_VALUE' => 0,
    'MODULE' => 0,
    'RECORD_STRUCTURE_MODEL' => 0,
    'KEY' => 0,
    'VALUE' => 0,
    'width11' => 0,
    'width14' => 0,
    'OCCUPY_COMPLETE_WIDTH' => 0,
  ),
  'has_nocache_code' => false,
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_57ab43bfc6a18')) {function content_57ab43bfc6a18($_smarty_tpl) {?>

<?php $_smarty_tpl->tpl_vars['width15'] = new Smarty_variable("15%", null, 0);?><?php $_smarty_tpl->tpl_vars['width14'] = new Smarty_variable("14%", null, 0);?><?php $_smarty_tpl->tpl_vars['width11'] = new Smarty_variable("11%", null, 0);?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="Авиа билеты"){?><?php $_smarty_tpl->tpl_vars['width15'] = new Smarty_variable("11%", null, 0);?><?php $_smarty_tpl->tpl_vars['width14'] = new Smarty_variable("11%", null, 0);?><?php $_smarty_tpl->tpl_vars['width11'] = new Smarty_variable("6%", null, 0);?><?php }?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="ЖД билеты"){?><?php $_smarty_tpl->tpl_vars['width15'] = new Smarty_variable("12%", null, 0);?><?php $_smarty_tpl->tpl_vars['width14'] = new Smarty_variable("13%", null, 0);?><?php $_smarty_tpl->tpl_vars['width11'] = new Smarty_variable("7%", null, 0);?><?php }?><?php  $_smarty_tpl->tpl_vars['delta'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['delta']->_loop = false;
 $_smarty_tpl->tpl_vars['key_air'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['check_array']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['delta']->key => $_smarty_tpl->tpl_vars['delta']->value){
$_smarty_tpl->tpl_vars['delta']->_loop = true;
 $_smarty_tpl->tpl_vars['key_air']->value = $_smarty_tpl->tpl_vars['delta']->key;
?><div class="row-fluid compressed flite" <?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?>style="margin-top: 25px;"<?php }?>><!-- Туда - Авиалинии --><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value!="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><div class="span3 width15" style="width: <?php echo $_smarty_tpl->tpl_vars['width15']->value;?>
; padding-right: 0;margin-left:1%"><div class="form-group"><?php $_smarty_tpl->tpl_vars['FIELD_MODEL'] = new Smarty_variable($_smarty_tpl->tpl_vars['BLOCK_FIELDS']->value['arr_airline'], null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_INFO"] = new Smarty_variable(Vtiger_Util_Helper::toSafeHTML(Zend_Json::encode($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldInfo())), null, 0);?><?php $_smarty_tpl->tpl_vars["SPECIAL_VALIDATOR"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getValidator(), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue'), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode('#',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value), null, 0);?><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?> <label for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
"><?php echo vtranslate($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('label'),$_smarty_tpl->tpl_vars['MODULE']->value);?>
 <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label> <?php }?><div class=""><select class='form-control  ' name='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
[]' <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> data-selected-value='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue');?>
'><option value=''><?php echo vtranslate('LBL_SELECT_OPTION','Vtiger');?>
</option><?php  $_smarty_tpl->tpl_vars['VALUE'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['VALUE']->_loop = false;
 $_smarty_tpl->tpl_vars['KEY'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['RECORD_STRUCTURE_MODEL']->value->getAirlinePikList(); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['VALUE']->key => $_smarty_tpl->tpl_vars['VALUE']->value){
$_smarty_tpl->tpl_vars['VALUE']->_loop = true;
 $_smarty_tpl->tpl_vars['KEY']->value = $_smarty_tpl->tpl_vars['VALUE']->key;
?><option value="<?php echo $_smarty_tpl->tpl_vars['KEY']->value;?>
" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]==$_smarty_tpl->tpl_vars['KEY']->value){?>selected<?php }?>><?php echo $_smarty_tpl->tpl_vars['VALUE']->value;?>
</option><?php } ?></select></div></div></div><?php }?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><div class="span3 width15 rail addShow" style="width: <?php echo $_smarty_tpl->tpl_vars['width15']->value;?>
; padding-right: 0;margin-left:1%"><div class="form-group"><?php $_smarty_tpl->tpl_vars['FIELD_MODEL'] = new Smarty_variable($_smarty_tpl->tpl_vars['BLOCK_FIELDS']->value['arr_airline'], null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_INFO"] = new Smarty_variable(Vtiger_Util_Helper::toSafeHTML(Zend_Json::encode($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldInfo())), null, 0);?><?php $_smarty_tpl->tpl_vars["SPECIAL_VALIDATOR"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getValidator(), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue'), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode('#',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value), null, 0);?><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?><label for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
"><?php echo vtranslate('Поезд',$_smarty_tpl->tpl_vars['MODULE']->value);?>
 <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><div class=""><input type="text" class='form-control  ' name='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
_rail[]' <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> data-selected-value='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue');?>
' value="<?php echo $_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value];?>
"></div></div></div><?php }?><!-- Туда - Рейс --><div class="span1" style="width: 5%; padding-right: 0;margin-left:1%"><div class="form-group"><?php $_smarty_tpl->tpl_vars['FIELD_MODEL'] = new Smarty_variable($_smarty_tpl->tpl_vars['BLOCK_FIELDS']->value['arr_flite'], null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_INFO"] = new Smarty_variable(Vtiger_Util_Helper::toSafeHTML(Zend_Json::encode($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldInfo())), null, 0);?><?php $_smarty_tpl->tpl_vars["SPECIAL_VALIDATOR"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getValidator(), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue'), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode('#',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value), null, 0);?><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value!="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><label class="ticket turPaket addShow" for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
"><?php echo vtranslate($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('label'),$_smarty_tpl->tpl_vars['MODULE']->value);?>
 <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><label class="rail addShow" for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
"><?php echo vtranslate('Номер',$_smarty_tpl->tpl_vars['MODULE']->value);?>
 <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><?php }?><div class="input-group"><input style="height: 26px;" id="<?php echo $_smarty_tpl->tpl_vars['MODULE']->value;?>
_editView_fieldName_<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('name');?>
" type="text" class="form-control" <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> name="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
[]"value="<?php echo $_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value];?>
"  /></div></div></div><div class="span1 width11" style="width: <?php echo $_smarty_tpl->tpl_vars['width11']->value;?>
; padding-right: 0;margin-left:1%"><div class="form-group"><?php $_smarty_tpl->tpl_vars['FIELD_MODEL'] = new Smarty_variable($_smarty_tpl->tpl_vars['BLOCK_FIELDS']->value['arr_type_flite'], null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_INFO"] = new Smarty_variable(Vtiger_Util_Helper::toSafeHTML(Zend_Json::encode($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldInfo())), null, 0);?><?php $_smarty_tpl->tpl_vars["SPECIAL_VALIDATOR"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getValidator(), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue'), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode('#',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value), null, 0);?><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value!="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><label class="ticket turPaket addShow" for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
">Тип рейса<?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><label class="rail addShow" for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
">Тип вагона<?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><?php }?><div class=""><select class='form-control  ' name='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
[]' <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> data-selected-value='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue');?>
'><option value=''><?php echo vtranslate('LBL_SELECT_OPTION','Vtiger');?>
</option><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value!="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><optgroup class="ticket turPaket addShow"><option value="регулярный" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]=='регулярный'){?>selected<?php }?>>Регуляный</option><option value="чартер" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]=='чартер'){?>selected<?php }?>>Чартер</option></optgroup><?php }?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><optgroup class="rail addShow"><option value="купе" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]=='купе'){?>selected<?php }?>>Купе</option><option value="СВ" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]=='СВ'){?>selected<?php }?>>СВ</option><option value="плацкард" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]=='плацкард'){?>selected<?php }?>>Плацкард</option><option value="женский" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]=='женский'){?>selected<?php }?>>Женский</option><option value="мужской" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]=='мужской'){?>selected<?php }?>>Мужской</option></optgroup><?php }?></select></div></div></div><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="Авиа билеты"){?><div class="span1 ticket addShow" style="width: 5%; padding-right: 0;margin-left:1%"><div class="form-group"><?php $_smarty_tpl->tpl_vars['FIELD_MODEL'] = new Smarty_variable($_smarty_tpl->tpl_vars['BLOCK_FIELDS']->value['arr_type_class'], null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_INFO"] = new Smarty_variable(Vtiger_Util_Helper::toSafeHTML(Zend_Json::encode($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldInfo())), null, 0);?><?php $_smarty_tpl->tpl_vars["SPECIAL_VALIDATOR"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getValidator(), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue'), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode('#',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value), null, 0);?><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?> <label for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
">Класс<?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><div class="input-group"><select class='form-control  ' name='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
[]' <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> data-selected-value='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue');?>
'><option value=''><?php echo vtranslate('LBL_SELECT_OPTION','Vtiger');?>
</option><option value="экономичный" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]=='экономичный'){?>selected<?php }?>>Экономичный</option><option value="бизнес" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]=='бизнес'){?>selected<?php }?>>Бизнес</option><option value="комфорт" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]=='комфорт'){?>selected<?php }?>>Повышенной комфортности</option></select></div></div></div><?php }?><!-- Туда - Откуда --><div class="span2 width15" style="width: <?php echo $_smarty_tpl->tpl_vars['width15']->value;?>
; padding-right: 0;margin-left:1%"><div class="form-group"><?php $_smarty_tpl->tpl_vars['FIELD_MODEL'] = new Smarty_variable($_smarty_tpl->tpl_vars['BLOCK_FIELDS']->value['arr_departure'], null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_INFO"] = new Smarty_variable(Vtiger_Util_Helper::toSafeHTML(Zend_Json::encode($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldInfo())), null, 0);?><?php $_smarty_tpl->tpl_vars["SPECIAL_VALIDATOR"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getValidator(), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue'), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode('#',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value), null, 0);?><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?> <label for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
"><?php echo vtranslate($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('label'),$_smarty_tpl->tpl_vars['MODULE']->value);?>
 <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><div class=""><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value!="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><select class='form-control ticket turPaket addShow ' name='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
[]' <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> data-selected-value='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue');?>
'><option value=''><?php echo vtranslate('LBL_SELECT_OPTION','Vtiger');?>
</option><?php  $_smarty_tpl->tpl_vars['VALUE'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['VALUE']->_loop = false;
 $_smarty_tpl->tpl_vars['KEY'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['RECORD_STRUCTURE_MODEL']->value->getAirportsPikList(); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['VALUE']->key => $_smarty_tpl->tpl_vars['VALUE']->value){
$_smarty_tpl->tpl_vars['VALUE']->_loop = true;
 $_smarty_tpl->tpl_vars['KEY']->value = $_smarty_tpl->tpl_vars['VALUE']->key;
?><option value="<?php echo $_smarty_tpl->tpl_vars['KEY']->value;?>
" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]==$_smarty_tpl->tpl_vars['KEY']->value){?>selected<?php }?>><?php echo $_smarty_tpl->tpl_vars['VALUE']->value;?>
</option><?php } ?></select><?php }?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><input value="<?php echo $_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value];?>
" class='form-control rail addShow ' name='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
_rail[]' <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> data-selected-value='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue');?>
'><?php }?></div></div></div><!-- Туда - время вылета--><div class="span3 width14" style="width: <?php echo $_smarty_tpl->tpl_vars['width14']->value;?>
; padding-right: 0;margin-left:1%"><div class="form-group"><?php $_smarty_tpl->tpl_vars['FIELD_MODEL'] = new Smarty_variable($_smarty_tpl->tpl_vars['BLOCK_FIELDS']->value['arr_time_departure'], null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_INFO"] = new Smarty_variable(Vtiger_Util_Helper::toSafeHTML(Zend_Json::encode($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldInfo())), null, 0);?><?php $_smarty_tpl->tpl_vars["SPECIAL_VALIDATOR"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getValidator(), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue'), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode('#',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value), null, 0);?><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value!="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><label class="ticket turPaket addShow" for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
"><?php echo vtranslate($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('label'),$_smarty_tpl->tpl_vars['MODULE']->value);?>
 <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><label class="rail addShow" for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
"><?php echo vtranslate('Отправление',$_smarty_tpl->tpl_vars['MODULE']->value);?>
 <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><?php }?><div class="input-group"><input style="height: 26px;" id="<?php echo $_smarty_tpl->tpl_vars['MODULE']->value;?>
_editView_fieldName_<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('name');?>
<?php echo $_smarty_tpl->tpl_vars['key_air']->value;?>
" type="text" class="form-control datetimepicker vilet arrvilet" onchange='validDate(this)' <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> name="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
[]"value="<?php echo $_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value];?>
"  /><span style="cursor: pointer;" class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div></div><!-- Туда - Куда --><div class="span2 width15" style="width: <?php echo $_smarty_tpl->tpl_vars['width15']->value;?>
; padding-right: 0;margin-left:1%"><div class="form-group"><?php $_smarty_tpl->tpl_vars['FIELD_MODEL'] = new Smarty_variable($_smarty_tpl->tpl_vars['BLOCK_FIELDS']->value['arr_arrival'], null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_INFO"] = new Smarty_variable(Vtiger_Util_Helper::toSafeHTML(Zend_Json::encode($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldInfo())), null, 0);?><?php $_smarty_tpl->tpl_vars["SPECIAL_VALIDATOR"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getValidator(), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue'), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode('#',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value), null, 0);?><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?>  <label for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
"><?php echo vtranslate($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('label'),$_smarty_tpl->tpl_vars['MODULE']->value);?>
 <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><div class=""><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value!="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><select class='form-control turPaket ticket addShow  ' name='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
[]' <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> data-selected-value='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue');?>
'><option value=''><?php echo vtranslate('LBL_SELECT_OPTION','Vtiger');?>
</option><?php  $_smarty_tpl->tpl_vars['VALUE'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['VALUE']->_loop = false;
 $_smarty_tpl->tpl_vars['KEY'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['RECORD_STRUCTURE_MODEL']->value->getAirportsPikList(); if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['VALUE']->key => $_smarty_tpl->tpl_vars['VALUE']->value){
$_smarty_tpl->tpl_vars['VALUE']->_loop = true;
 $_smarty_tpl->tpl_vars['KEY']->value = $_smarty_tpl->tpl_vars['VALUE']->key;
?><option value="<?php echo $_smarty_tpl->tpl_vars['KEY']->value;?>
" <?php if ($_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]==$_smarty_tpl->tpl_vars['KEY']->value){?>selected<?php }?>><?php echo $_smarty_tpl->tpl_vars['VALUE']->value;?>
</option><?php } ?></select><?php }?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><input value="<?php echo $_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value];?>
" class='form-control rail addShow ' name='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
_rail[]' <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> data-selected-value='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue');?>
'><?php }?></div></div></div><!-- Туда - время прибытия --><div class="span3 width14" style="width: <?php echo $_smarty_tpl->tpl_vars['width14']->value;?>
; padding-right: 0;margin-left:1%"><div class="form-group"><?php $_smarty_tpl->tpl_vars['FIELD_MODEL'] = new Smarty_variable($_smarty_tpl->tpl_vars['BLOCK_FIELDS']->value['arr_time_arrival'], null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_INFO"] = new Smarty_variable(Vtiger_Util_Helper::toSafeHTML(Zend_Json::encode($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldInfo())), null, 0);?><?php $_smarty_tpl->tpl_vars["SPECIAL_VALIDATOR"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getValidator(), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue'), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode('#',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value), null, 0);?><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value!="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><label class="ticket turPaket addShow" for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
"><?php echo vtranslate($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('label'),$_smarty_tpl->tpl_vars['MODULE']->value);?>
 <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><label class="rail addShow" for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
"><?php echo vtranslate('Прибытие',$_smarty_tpl->tpl_vars['MODULE']->value);?>
 <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><?php }?><div class="input-group"><input style="height: 26px;" id="<?php echo $_smarty_tpl->tpl_vars['MODULE']->value;?>
_editView_fieldName_<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('name');?>
<?php echo $_smarty_tpl->tpl_vars['key_air']->value;?>
" type="text" class="form-control datetimepicker prilet arrprilet" onchange='validDate2(this)' <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> name="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
[]"value="<?php echo $_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value];?>
"  /><span style="cursor: pointer;" class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div></div><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="Авиа билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value=="ЖД билеты"){?><div class="span1 ticket addShow" style="width: 13%; padding-right: 0;margin-left:1%"><div class="form-group"><?php $_smarty_tpl->tpl_vars['FIELD_MODEL'] = new Smarty_variable($_smarty_tpl->tpl_vars['BLOCK_FIELDS']->value['arr_list_pass'], null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_INFO"] = new Smarty_variable(Vtiger_Util_Helper::toSafeHTML(Zend_Json::encode($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldInfo())), null, 0);?><?php $_smarty_tpl->tpl_vars["SPECIAL_VALIDATOR"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getValidator(), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue'), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode('#',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode(',',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value]), null, 0);?><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?>  <label for="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
">Пасажиры<?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> <span class="redColor">*</span> <?php }?></label><?php }?><div class="input-group"><select class='chzn-select form-control <?php if ($_smarty_tpl->tpl_vars['OCCUPY_COMPLETE_WIDTH']->value){?> row-fluid-fluid <?php }?> listTurist listTuristPrice' multiple name='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
[<?php echo $_smarty_tpl->tpl_vars['key_air']->value;?>
][]' <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> data-selected-value='<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue');?>
' style="width:160px;"><?php  $_smarty_tpl->tpl_vars['KEY'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['KEY']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['FIELD_VALUE']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['KEY']->key => $_smarty_tpl->tpl_vars['KEY']->value){
$_smarty_tpl->tpl_vars['KEY']->_loop = true;
?><option value="<?php echo $_smarty_tpl->tpl_vars['KEY']->value;?>
" selected ><?php echo $_smarty_tpl->tpl_vars['KEY']->value;?>
</option><?php } ?></select></div></div></div><?php }?><div class="span1" style="width: 2%; padding-right: 0;margin-left:1%"><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?> <label>&nbsp;</label><?php }?><div class="form-group addButtonContainer"><?php if ($_smarty_tpl->tpl_vars['key_air']->value==0){?>   <button class="btn btn-default add-row-fluid" onclick="addFlite(event,this);"><i class="fa fa-plus"></i></button><?php }else{ ?><button class="btn btn-default del-row-fluid" onclick="deleteFlite(event, this)"><i class="fa fa-times"></i></button><?php }?></div></div><?php if ($_smarty_tpl->tpl_vars['opportunity_type']->value=="Авиа билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value=="ЖД билеты"||$_smarty_tpl->tpl_vars['opportunity_type']->value==''){?><div class="span4 ticket rai addShow" style="width: 100px; padding-right: 0;margin-left:1%"><span>Цена билета:</span></div><div class="span2 ticket rai addShow" style="width: 13%; padding-right: 0;margin-left:1%"><div class="form-group form-group-required"><?php $_smarty_tpl->tpl_vars['FIELD_MODEL'] = new Smarty_variable($_smarty_tpl->tpl_vars['BLOCK_FIELDS']->value['ticketprice_arr'], null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_INFO"] = new Smarty_variable(Vtiger_Util_Helper::toSafeHTML(Zend_Json::encode($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldInfo())), null, 0);?><?php $_smarty_tpl->tpl_vars["SPECIAL_VALIDATOR"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getValidator(), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('fieldvalue'), null, 0);?><?php $_smarty_tpl->tpl_vars["FIELD_VALUE"] = new Smarty_variable(explode('#',$_smarty_tpl->tpl_vars['FIELD_VALUE']->value), null, 0);?><div class="input-group"><input id="<?php echo $_smarty_tpl->tpl_vars['MODULE']->value;?>
_editView_fieldName_<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->get('name');?>
_<?php echo $_smarty_tpl->tpl_vars['key_air']->value;?>
" type="text" class="form-control ticketprice"  <?php if ($_smarty_tpl->tpl_vars['FIELD_MODEL']->value->isMandatory()==true){?> required<?php }?> name="<?php echo $_smarty_tpl->tpl_vars['FIELD_MODEL']->value->getFieldName();?>
[]"value="<?php echo $_smarty_tpl->tpl_vars['FIELD_VALUE']->value[$_smarty_tpl->tpl_vars['key_air']->value];?>
"  /><span class="input-group-addon"><i class="fa fa-rub"></i></span></div></div></div><div class="span4 ticket rai addShow" style="width: 300px; padding-right: 0;margin-left:1%"><span>*Указывается стоимость на одного пассажира</span></div><?php }?></div><hr /><?php } ?><?php }} ?>